o_width = 70
o_height = 136
sh_th = 4
front_th = 6
fillet_r = 3
### Card pocket
card_w = 54.5
card_h = 50 # total 85, 50 is the size of the pocket
card_th = 1.2
### Keyfob pocket
keyfob_d = 32.5
keyfob_th = 4.5
### Display
# display hole
disp_y_offset = -20
disp_x_offset = 5
dhh = 27
dhw = 28
# display size
dh = 30
dw = 43.5
dwextra = 7
w1 = 2 # clip width
h2 = 6.3 # clip height
disp_wth = 3
rod_d = 1 # clip protusion diameter
# inserts and screws
insert_l = 4.5
insert_r = 4.2/2
insert_sr = 1.75
screw_hole_r = 3.2/2
screw_head_r = 3
screw_head_h = 2.5
mh_inset = 4
# Middle section
mid_th = 2
# Switch
sw_w1 = 5
sw_w2 = 6.4
sw_l1 = 15
sw_l2 = 20
sw_h2 = 13-1.25
# Bottom section
bottom_th = 33 + sh_th
gland_r = 13/2 # PG7
gland_z = 15
gland_cc = 30
wh_dist = 40
wh_height = 15
pcb_holes = ((89, 74), (63, 99), (63, 161), (104, 161))
